feat: add profile page
mindenit/glimpse pull request #6
Opened 2024-11-30 11:54 UTC by Mykhailo-Parm

2024-11-30 20:13 UTC, OneLiL05 requested changes

2024-11-30 20:13 UTC, OneLiL05 commented on components/ui/TheStar.vue
> +<template>
Rewrite from [Options](https://vuejs.org/guide/introduction.html#options-api) to [Composition API](https://vuejs.org/guide/introduction.html#composition-api), change file structure to:

```vue
<script setup></script>

<template></template>
```

2024-12-01 14:47 UTC, OneLiL05 requested changes

2024-12-01 14:47 UTC, OneLiL05 commented on components/ui/TheStar.vue
> +const value = ref(props.modelValue);
Re-write using `useVModel` composable from `vueuse` library. For more info refer to the [docs](https://vueuse.org/core/useVModel/)

2024-12-01 14:47 UTC, OneLiL05 commented on components/ui/TheStar.vue
> +const props = defineProps({
Re-write typings according to the [typing component props docs](https://vuejs.org/guide/typescript/composition-api.html#typing-component-props)

For default values use reactive props destructure, for more info refer to the [props default values docs](https://vuejs.org/guide/typescript/composition-api.html#props-default-values)

2024-12-01 14:47 UTC, OneLiL05 commented on components/ui/TheStar.vue
> +const emit = defineEmits(['update:modelValue']);
Re-write according to [typing component emits docs](https://vuejs.org/guide/typescript/composition-api.html#typing-component-emits)

2024-12-01 21:36 UTC, OneLiL05 requested changes

2024-12-01 21:36 UTC, OneLiL05 commented on components/ui/TheStar.vue
> +const { modelValue = 0, maxStars = 5 } = props
Re-write it to the following:

```ts
const { maxStars = 5 } = defineProps<StarRatingProps>()
```

You don't need to define default value for `modelValue` prop here, since you've already done it in `useVModel` composable.

Your next line is kinda irrelevant, since props will lose their reactivity and conception of `reactive props desctructure` will not work in this case

2024-12-01 21:36 UTC, OneLiL05 commented on components/ui/TheStar.vue
> +const value = useVModel(props, 'modelValue', emit, {
Rename `value` to `model`

2024-12-01 21:36 UTC, OneLiL05 commented on components/ui/TheStar.vue
> +  value.value = newRating
Since model value is prop, you shouldn't mutate it manually, use `update:modelValue` emit instead, so you can remove `updateRating` function and just call emit in `template`

2024-12-02 18:15 UTC, dimaP2341 commented on components/ui/TheStar.vue
> +const model = useVModel(props, 'modelValue', emit, {
<img width="1089" alt="Screenshot 2024-12-02 at 20 04 03" src="https://github.com/user-attachments/assets/724977e3-ec98-42c3-8572-bbedcafb988f">

2024-12-02 18:16 UTC, dimaP2341 commented on components/ui/TheStar.vue
> +const model = useVModel(props, 'modelValue', emit, {
instead of const { maxStars = 5 } = defineProps<StarRatingProps>()  I write const props = defineProps<StarRatingProps>()

2024-12-02 18:50 UTC, OneLiL05 requested changes

2024-12-02 18:50 UTC, OneLiL05 commented on components/ui/TheStar.vue
> +      v-for="i in props.maxStars"
In the template you don't need to write `props.propName`, you can use shorthand by just writing `propName`

2024-12-02 18:50 UTC, OneLiL05 commented on components/ui/TheStar.vue
> +  modelValue: number
Make props optional again

2024-12-02 18:57 UTC, OneLiL05 submitted a review, later dismissed

2024-12-02 18:59 UTC, merged